/**
 * Cloudinary storage service.
 *
 * Abstracts all Cloudinary SDK interactions behind a clean interface.
 * The rest of the application never touches the Cloudinary SDK directly.
 *
 * Architecture:
 *   1. Backend generates a signed upload signature + params
 *   2. Browser uploads directly to Cloudinary (image never hits Express)
 *   3. Backend confirms the upload and stores the public_id
 *
 * If we ever migrate from Cloudinary to S3/Azure/R2, only this file changes.
 */

import { v2 as cloudinary } from "cloudinary";
import { env } from "../config/env.js";

// ─── Configuration ────────────────────────────────────────

function ensureConfigured() {
  if (!env.CLOUDINARY_CLOUD_NAME || !env.CLOUDINARY_API_KEY || !env.CLOUDINARY_API_SECRET) {
    throw new Error(
      "Cloudinary is not configured. Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET."
    );
  }

  cloudinary.config({
    cloud_name: env.CLOUDINARY_CLOUD_NAME,
    api_key: env.CLOUDINARY_API_KEY,
    api_secret: env.CLOUDINARY_API_SECRET,
    secure: true,
  });
}

export function isConfigured(): boolean {
  return !!(env.CLOUDINARY_CLOUD_NAME && env.CLOUDINARY_API_KEY && env.CLOUDINARY_API_SECRET);
}

// ─── Signed Upload Params ─────────────────────────────────

export interface SignedUploadParams {
  signature: string;
  timestamp: number;
  cloudName: string;
  apiKey: string;
  folder: string;
  publicId: string;
  uploadUrl: string;
  params: Record<string, string>;
}

/**
 * Generate signed parameters for a direct browser-to-Cloudinary upload.
 *
 * The browser will POST the file + these params to Cloudinary's upload URL.
 * The signature ensures only our backend can authorize uploads.
 *
 * @param userId   The authenticated user's ID (used to scope the folder)
 * @param publicId The unique blob name (UUID generated by caller)
 */
export function generateSignedUploadParams(
  userId: string,
  publicId: string
): SignedUploadParams {
  ensureConfigured();

  const folder = `modhuralap/users/${userId}`;
  const timestamp = Math.round(Date.now() / 1000);

  // Parameters that get signed — keep minimal to prevent mismatch
  const paramsToSign = {
    folder,
    public_id: publicId,
    timestamp,
  };

  const signature = cloudinary.utils.api_sign_request(
    paramsToSign,
    env.CLOUDINARY_API_SECRET!
  );

  return {
    signature,
    timestamp,
    cloudName: env.CLOUDINARY_CLOUD_NAME!,
    apiKey: env.CLOUDINARY_API_KEY!,
    folder,
    publicId,
    uploadUrl: `https://api.cloudinary.com/v1_1/${env.CLOUDINARY_CLOUD_NAME}/image/upload`,
    params: {
      api_key: env.CLOUDINARY_API_KEY!,
      timestamp: String(timestamp),
      signature,
      folder,
      public_id: publicId,
    },
  };
}

/**
 * Generate a Cloudinary delivery URL with transformations.
 *
 * Cloudinary automatically transforms images on-the-fly:
 *   - thumbnail: 150x150 face-crop
 *   - card: 500x500 fill
 *   - profile: 1200x1200 limit
 *   - original: no transformation
 *
 * NOTE: We build the URL manually instead of using cloudinary.url()
 * because the SDK's `transformation` option as a string gets treated
 * as a *named transformation* (prefixed with `t_`), resulting in 400 errors.
 *
 * @param publicId  The Cloudinary public_id (stored in DB as storageKey)
 * @param variant   The size variant to generate
 */
export function getImageUrl(
  publicId: string | null | undefined,
  variant: "thumbnail" | "card" | "profile" | "original" = "profile"
): string | null {
  if (!publicId) return null;

  // If it's already a full URL (legacy data), return as-is
  if (publicId.startsWith("http://") || publicId.startsWith("https://")) {
    return publicId;
  }

  if (!isConfigured()) return null;

  const transformations: Record<string, string> = {
    thumbnail: "c_fill,g_face,w_150,h_150,q_auto,f_auto",
    card: "c_fill,g_face,w_500,h_500,q_auto,f_auto",
    profile: "c_limit,w_1200,h_1200,q_auto,f_auto",
    original: "q_auto,f_auto",
  };

  const transform = transformations[variant];

  // Build URL manually: https://res.cloudinary.com/{cloud}/image/upload/{transforms}/{publicId}
  return `https://res.cloudinary.com/${env.CLOUDINARY_CLOUD_NAME}/image/upload/${transform}/${publicId}`;
}

/**
 * Resolve a storageKey (Cloudinary public_id) to a usable image URL.
 * Default variant is "profile" (1200x1200 max).
 */
export function resolveImageUrl(
  storageKey: string | null | undefined,
  variant: "thumbnail" | "card" | "profile" | "original" = "profile"
): string | null {
  return getImageUrl(storageKey, variant);
}

// ─── Resource Management ──────────────────────────────────

/**
 * Check if a resource exists in Cloudinary.
 */
export async function resourceExists(publicId: string): Promise<boolean> {
  ensureConfigured();
  try {
    await cloudinary.api.resource(publicId);
    return true;
  } catch {
    return false;
  }
}

/**
 * Get resource details from Cloudinary.
 */
export async function getResourceDetails(publicId: string) {
  ensureConfigured();
  try {
    const result = await cloudinary.api.resource(publicId);
    return {
      publicId: result.public_id,
      format: result.format,
      width: result.width,
      height: result.height,
      bytes: result.bytes,
      url: result.secure_url,
      createdAt: result.created_at,
    };
  } catch {
    return null;
  }
}

/**
 * Delete a resource from Cloudinary. Returns true if deleted.
 */
export async function deleteResource(publicId: string): Promise<boolean> {
  ensureConfigured();
  try {
    const result = await cloudinary.uploader.destroy(publicId);
    return result.result === "ok";
  } catch {
    return false;
  }
}

// ─── Utility: Resolve avatars on query results ────────────

/**
 * Transform any object (or nested user object) that has an `avatar` field
 * from a Cloudinary public_id to a delivery URL.
 *
 * Works on:
 *   - { avatar: "modhuralap/users/xxx/uuid" }      → resolves avatar
 *   - { user: { avatar: "..." } }                   → resolves user.avatar
 *   - [{ avatar: "..." }, { avatar: "..." }]        → resolves all
 *   - [{ user: { avatar: "..." } }]                 → resolves all
 */
export function resolveAvatars<T>(data: T, variant: "thumbnail" | "card" | "profile" = "profile"): T {
  if (!data) return data;

  if (Array.isArray(data)) {
    return data.map((item) => resolveAvatars(item, variant)) as T;
  }

  if (typeof data === "object") {
    const obj = { ...data } as Record<string, unknown>;

    // Resolve top-level avatar
    if ("avatar" in obj && typeof obj.avatar === "string") {
      obj.avatar = resolveImageUrl(obj.avatar as string, variant);
    }

    // Resolve nested user.avatar
    if ("user" in obj && obj.user && typeof obj.user === "object") {
      obj.user = resolveAvatars(obj.user, variant);
    }

    // Resolve nested participant objects (for chat)
    if ("participant1User" in obj && obj.participant1User) {
      obj.participant1User = resolveAvatars(obj.participant1User, variant);
    }
    if ("participant2User" in obj && obj.participant2User) {
      obj.participant2User = resolveAvatars(obj.participant2User, variant);
    }

    // Resolve client/companion in bookings
    if ("client" in obj && obj.client && typeof obj.client === "object") {
      obj.client = resolveAvatars(obj.client, variant);
    }
    if ("companionProfile" in obj && obj.companionProfile && typeof obj.companionProfile === "object") {
      obj.companionProfile = resolveAvatars(obj.companionProfile, variant);
    }

    return obj as T;
  }

  return data;
}
