/**
 * Mock data for the Explore Male Dating Companions page.
 *
 * ⚠️  DEV ONLY — All data here is static/hardcoded for UI development.
 * Replace with real API calls when backend is ready.
 *
 * Each companion object maps to the API response shape:
 *   GET /api/companions?gender=male&page=1&limit=8
 */

export interface Companion {
  id: string;
  name: string;
  age: number;
  profession: string;
  city: string;
  interests: string[];
  pricePerHour: number;
  rating: number;
  reviews: number;
  responseRate: number;
  isVerified: boolean;
  avatar: string | null;
  bio: string;
  languages: string[];
  gender: "male" | "female" | "other";
}

export const maleCompanions: Companion[] = [
  {
    id: "mc-001",
    name: "Arjun Mehta",
    age: 28,
    profession: "Marketing Professional",
    city: "Kolkata",
    interests: ["Travel", "Food", "Movies"],
    pricePerHour: 2500,
    rating: 4.8,
    reviews: 112,
    responseRate: 95,
    isVerified: true,
    avatar: null,
    bio: "Loves exploring local food joints and sharing travel stories.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "male",
  },
  {
    id: "mc-002",
    name: "Rohan Sharma",
    age: 32,
    profession: "Entrepreneur",
    city: "Kolkata",
    interests: ["Business", "Travel", "Fitness"],
    pricePerHour: 3000,
    rating: 4.9,
    reviews: 87,
    responseRate: 92,
    isVerified: true,
    avatar: null,
    bio: "Passionate about business conversations and fitness routines.",
    languages: ["English", "Hindi"],
    gender: "male",
  },
  {
    id: "mc-003",
    name: "Karan Singh",
    age: 26,
    profession: "Software Engineer",
    city: "Kolkata",
    interests: ["Gaming", "Music", "Travel"],
    pricePerHour: 2200,
    rating: 4.7,
    reviews: 64,
    responseRate: 98,
    isVerified: true,
    avatar: null,
    bio: "Tech enthusiast who enjoys gaming sessions and live music.",
    languages: ["English", "Hindi", "Punjabi"],
    gender: "male",
  },
  {
    id: "mc-004",
    name: "Siddharth Kapoor",
    age: 30,
    profession: "Lawyer",
    city: "Kolkata",
    interests: ["Debates", "Books", "Dining"],
    pricePerHour: 3500,
    rating: 4.9,
    reviews: 98,
    responseRate: 94,
    isVerified: true,
    avatar: null,
    bio: "Thoughtful conversationalist with a passion for fine dining.",
    languages: ["English", "Hindi"],
    gender: "male",
  },
  {
    id: "mc-005",
    name: "Aman Verma",
    age: 27,
    profession: "Fitness Coach",
    city: "Kolkata",
    interests: ["Fitness", "Sports", "Adventure"],
    pricePerHour: 2800,
    rating: 4.8,
    reviews: 76,
    responseRate: 97,
    isVerified: true,
    avatar: null,
    bio: "Adventure lover who combines fitness with meaningful experiences.",
    languages: ["English", "Hindi"],
    gender: "male",
  },
  {
    id: "mc-006",
    name: "Vikram Desai",
    age: 34,
    profession: "Photographer",
    city: "Kolkata",
    interests: ["Photography", "Travel", "Art"],
    pricePerHour: 3200,
    rating: 4.7,
    reviews: 53,
    responseRate: 90,
    isVerified: true,
    avatar: null,
    bio: "Captures moments and stories through the lens of creativity.",
    languages: ["English", "Hindi", "Gujarati"],
    gender: "male",
  },
  {
    id: "mc-007",
    name: "Kabir Khan",
    age: 29,
    profession: "Business Analyst",
    city: "Kolkata",
    interests: ["Business", "Technology", "Music"],
    pricePerHour: 2600,
    rating: 4.6,
    reviews: 42,
    responseRate: 93,
    isVerified: true,
    avatar: null,
    bio: "Analytical mind with a creative soul — loves tech and music.",
    languages: ["English", "Hindi", "Urdu"],
    gender: "male",
  },
  {
    id: "mc-008",
    name: "Dev Patel",
    age: 31,
    profession: "Event Host",
    city: "Kolkata",
    interests: ["Social", "Travel", "Food"],
    pricePerHour: 3000,
    rating: 4.8,
    reviews: 89,
    responseRate: 96,
    isVerified: true,
    avatar: null,
    bio: "Natural entertainer who makes every gathering unforgettable.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "male",
  },
];

/** Category filter tabs matching the reference design. */
export const femaleCompanions: Companion[] = [
  {
    id: "fc-001",
    name: "Aanya Roy",
    age: 27,
    profession: "Content Strategist",
    city: "Kolkata",
    interests: ["Travel", "Food", "Photography"],
    pricePerHour: 2400,
    rating: 4.9,
    reviews: 121,
    responseRate: 96,
    isVerified: true,
    avatar: null,
    bio: "Creative soul who enjoys thoughtful conversations and city walks.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "female",
  },
  {
    id: "fc-002",
    name: "Ishita Sen",
    age: 30,
    profession: "Designer",
    city: "Kolkata",
    interests: ["Art", "Music", "Cafe Hopping"],
    pricePerHour: 2900,
    rating: 4.8,
    reviews: 101,
    responseRate: 94,
    isVerified: true,
    avatar: null,
    bio: "Loves art spaces, music nights and meaningful connection over coffee.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "female",
  },
  {
    id: "fc-003",
    name: "Rhea Malhotra",
    age: 26,
    profession: "Software Engineer",
    city: "Kolkata",
    interests: ["Movies", "Travel", "Gaming"],
    pricePerHour: 2200,
    rating: 4.7,
    reviews: 68,
    responseRate: 98,
    isVerified: true,
    avatar: null,
    bio: "Tech-savvy and warm-hearted, with a love for spontaneous plans.",
    languages: ["English", "Hindi"],
    gender: "female",
  },
  {
    id: "fc-004",
    name: "Naina Banerjee",
    age: 29,
    profession: "Lawyer",
    city: "Kolkata",
    interests: ["Books", "Conversation", "Dining"],
    pricePerHour: 3300,
    rating: 4.9,
    reviews: 110,
    responseRate: 95,
    isVerified: true,
    avatar: null,
    bio: "Thoughtful, graceful, and always up for a good conversation.",
    languages: ["English", "Bengali", "Hindi"],
    gender: "female",
  },
  {
    id: "fc-005",
    name: "Meher Kapoor",
    age: 28,
    profession: "Brand Manager",
    city: "Kolkata",
    interests: ["Fitness", "Travel", "Shopping"],
    pricePerHour: 2700,
    rating: 4.8,
    reviews: 80,
    responseRate: 97,
    isVerified: true,
    avatar: null,
    bio: "Confident, polished and passionate about memorable experiences.",
    languages: ["English", "Hindi"],
    gender: "female",
  },
  {
    id: "fc-006",
    name: "Sana Dutta",
    age: 31,
    profession: "Photographer",
    city: "Kolkata",
    interests: ["Photography", "Art", "Travel"],
    pricePerHour: 3100,
    rating: 4.8,
    reviews: 56,
    responseRate: 92,
    isVerified: true,
    avatar: null,
    bio: "Creative and expressive, with a sharp eye for beautiful moments.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "female",
  },
  {
    id: "fc-007",
    name: "Tania Gupta",
    age: 25,
    profession: "Consultant",
    city: "Kolkata",
    interests: ["Business", "Music", "Culture"],
    pricePerHour: 2500,
    rating: 4.7,
    reviews: 43,
    responseRate: 94,
    isVerified: true,
    avatar: null,
    bio: "Warm and intelligent with a love for meaningful cultural outings.",
    languages: ["English", "Hindi"],
    gender: "female",
  },
  {
    id: "fc-008",
    name: "Mira Das",
    age: 32,
    profession: "Event Curator",
    city: "Kolkata",
    interests: ["Events", "Dining", "Travel"],
    pricePerHour: 3400,
    rating: 4.9,
    reviews: 91,
    responseRate: 96,
    isVerified: true,
    avatar: null,
    bio: "Curates magical experiences and genuinely enjoys thoughtful company.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "female",
  },
];

export const companionCategories = [
  "All Men",
  "Dating",
  "Hangout",
  "Travel",
  "Dinner",
  "Events",
  "Fitness",
  "Creative",
  "Professional",
  "More",
] as const;

export const femaleCompanionCategories = [
  "All Women",
  "Dating",
  "Hangout",
  "Travel",
  "Dinner",
  "Events",
  "Fitness",
  "Creative",
  "Professional",
  "More",
] as const;

export const queerCompanions: Companion[] = [
  {
    id: "qc-001",
    name: "Ari Dutta",
    age: 29,
    profession: "Creative Strategist",
    city: "Kolkata",
    interests: ["Travel", "Art", "Coffee"],
    pricePerHour: 2800,
    rating: 4.9,
    reviews: 133,
    responseRate: 97,
    isVerified: true,
    avatar: null,
    bio: "Warm, expressive, and always up for a thoughtful conversation.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
  {
    id: "qc-002",
    name: "Nisha Sen",
    age: 27,
    profession: "Photographer",
    city: "Kolkata",
    interests: ["Photography", "Travel", "Music"],
    pricePerHour: 3100,
    rating: 4.8,
    reviews: 122,
    responseRate: 96,
    isVerified: true,
    avatar: null,
    bio: "Loves capturing moments and enjoying meaningful, genuine connection.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
  {
    id: "qc-003",
    name: "Ritvik Roy",
    age: 31,
    profession: "Product Designer",
    city: "Kolkata",
    interests: ["Gaming", "Tech", "Travel"],
    pricePerHour: 2900,
    rating: 4.7,
    reviews: 82,
    responseRate: 95,
    isVerified: true,
    avatar: null,
    bio: "Chill, creative and comfortable in thoughtful, open conversations.",
    languages: ["English", "Hindi"],
    gender: "other",
  },
  {
    id: "qc-004",
    name: "Mira Nair",
    age: 26,
    profession: "Community Manager",
    city: "Kolkata",
    interests: ["Dining", "Events", "Culture"],
    pricePerHour: 2600,
    rating: 4.9,
    reviews: 117,
    responseRate: 98,
    isVerified: true,
    avatar: null,
    bio: "Brings warmth, honesty and a great sense of joy to any connection.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
  {
    id: "qc-005",
    name: "Kian Bose",
    age: 30,
    profession: "Event Curator",
    city: "Kolkata",
    interests: ["Events", "Music", "Travel"],
    pricePerHour: 3400,
    rating: 4.8,
    reviews: 74,
    responseRate: 94,
    isVerified: true,
    avatar: null,
    bio: "Loves curated experiences, exciting conversations, and confident company.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
  {
    id: "qc-006",
    name: "Saanvi Das",
    age: 28,
    profession: "Brand Strategist",
    city: "Kolkata",
    interests: ["Shopping", "Food", "Art"],
    pricePerHour: 3000,
    rating: 4.8,
    reviews: 68,
    responseRate: 96,
    isVerified: true,
    avatar: null,
    bio: "Expressive, sincere, and always ready for a great city outing.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
  {
    id: "qc-007",
    name: "Aarav Sen",
    age: 33,
    profession: "Consultant",
    city: "Kolkata",
    interests: ["Business", "Culture", "Travel"],
    pricePerHour: 3200,
    rating: 4.7,
    reviews: 57,
    responseRate: 92,
    isVerified: true,
    avatar: null,
    bio: "Thoughtful partner with a drive for meaningful experience and easy energy.",
    languages: ["English", "Hindi"],
    gender: "other",
  },
  {
    id: "qc-008",
    name: "Tania Bose",
    age: 25,
    profession: "Illustrator",
    city: "Kolkata",
    interests: ["Art", "Coffee", "Music"],
    pricePerHour: 2500,
    rating: 4.9,
    reviews: 104,
    responseRate: 97,
    isVerified: true,
    avatar: null,
    bio: "Creates beautiful moments and enjoys honest, comfortable company.",
    languages: ["English", "Hindi", "Bengali"],
    gender: "other",
  },
];

export const queerCompanionCategories = [
  "All Queer",
  "LGBTQ+ Friendly",
  "Lesbian",
  "Gay",
  "Bisexual",
  "Transgender",
  "Non-binary",
  "Queer",
  "More",
] as const;

/** Interest filter options (checkbox list). */
export const interestFilters = [
  "Dating",
  "Travel",
  "Food & Dining",
  "Movies",
  "Music",
  "Sports",
  "Fitness",
  "Art & Culture",
  "Business",
  "Gaming",
  "More",
] as const;

/** Trust badges for the hero section. */
export const exploreTrustBadges = [
  { icon: "shield-check", label: "Verified Profiles", description: "(100% Genuine)" },
  { icon: "lock", label: "Safe & Discreet", description: "Your Privacy Matters" },
  { icon: "heart", label: "Respectful", description: "& Well-Mannered" },
  { icon: "age", label: "18+ Only", description: "(Verified Age)" },
] as const;

/** Value propositions row. */
export const exploreValueProps = [
  { icon: "shield-check", title: "100% Verified", description: "ID & profile verification" },
  { icon: "lock", title: "Discreet & Private", description: "Your data stays safe" },
  { icon: "calendar", title: "Flexible Bookings", description: "Choose what suits you" },
  { icon: "users", title: "Real People", description: "Meaningful experiences" },
] as const;
